spring.application.name=employee-management-api
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/employee-management}

app.security.encryption-key=${ENCRYPTION_SECRET_KEY:c3VwZXJzZWNyZXRlc3RyaW5nMTIzNDU2Nzg5MDE2}

# Actuator Configuration
management.endpoints.web.base-path=/api/actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
